
name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' 

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: env-cmd -f .env npm run build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting -P ccny-shuttle-a35ec
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
